//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.ControleFinanceiro.Infra.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LGroup.ControleFinanceiro.Infra.Common.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível fazer um agendamento aos sábados ou domingos.
        /// </summary>
        public static string AgendamentoSabadoDomingoInvalido {
            get {
                return ResourceManager.GetString("AgendamentoSabadoDomingoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do pagamento está inválida.
        /// </summary>
        public static string DataPagamentoInvalida {
            get {
                return ResourceManager.GetString("DataPagamentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi(ram) informado(s) o(s) dia(s) para o agendamento.
        /// </summary>
        public static string DatasNaoInformadasNoAgendamento {
            get {
                return ResourceManager.GetString("DatasNaoInformadasNoAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do vencimento do pagamento está inválida.
        /// </summary>
        public static string DataVencimentoPagamentoInvalida {
            get {
                return ResourceManager.GetString("DataVencimentoPagamentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do pagamento está inválida.
        /// </summary>
        public static string DescricaoPagamentoInvalida {
            get {
                return ResourceManager.GetString("DescricaoPagamentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado no sistema.
        /// </summary>
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro não identificado.
        /// </summary>
        public static string ErroNaoIdentificado {
            get {
                return ResourceManager.GetString("ErroNaoIdentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento do débito está inválido.
        /// </summary>
        public static string PagamentoDebitoInvalido {
            get {
                return ResourceManager.GetString("PagamentoDebitoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento está inválido.
        /// </summary>
        public static string PagamentoInvalido {
            get {
                return ResourceManager.GetString("PagamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O crédito do recebimento está inválido.
        /// </summary>
        public static string RecebimentoCreditoInvalido {
            get {
                return ResourceManager.GetString("RecebimentoCreditoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não foi informado corretamente.
        /// </summary>
        public static string RecebimentoNomeVazio {
            get {
                return ResourceManager.GetString("RecebimentoNomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(s) registro(s) foi(ram) salvo(s) com sucesso.
        /// </summary>
        public static string SalvoComSucesso {
            get {
                return ResourceManager.GetString("SalvoComSucesso", resourceCulture);
            }
        }
    }
}
